export default {
    base: '/movie',

    details: '/{id}',
    accountStates: '/{id}/account_states',
    alternativeTitles: '/{id}/alternative_titles',
    changes: '/{id}/changes',
    credits: '/{id}/credits',
    externalIds: '/{id}/external_ids',
    images: '/{id}/images',
    keywords: '/{id}keywords',
    releaseDates: '/{id}/release_dates',
    videos: '/{id}/videos',
    translations: '/{id}/translations',
    recommendations: '/{id}/recomendations',
    similar: '/{id}/similar',
    reviews: '/{id}/reviews',
    lists: '/{id}/lists',
    rating: '/{id}/rating',
    latest: '/latest',
    nowPlaying: '/now_playing',
    popular: '/popular',
    topRated: '/top_rated',
    upcoming: '/upcoming',
};
