export default {
    base: '/tv',

    details: '/{id}',
    accountStates: '/{id}/account_states',
    alternativeTitles: '/{id}/alternative_titles',
    changes: '/{id}/changes',
    contentRatings: '/{id}/content_ratings',
    credits: '/{id}/credits',
    episodeGroups: '/{id}/episode_groups',
    externalIds: '/{id}/external_ids',
    images: '/{id}/images',
    keywords: '/{id}keywords',
    recommendations: '/{id}/recomendations',
    reviews: '/{id}/reviews',
    screenedTheartically: '/{id}/screened_theartically',
    similar: '/{id}/similar',
    translations: '/{id}/translations',
    videos: '/{id}/videos',
    rating: '/{id}/rating',
    latest: '/latest',
    airingToday: '/airing_today',
    onTheAir: '/on_the_air',
    popular: '/popular',
    topRated: '/top_rated',
};
